// sr_panel/src/components/SideBar.vue
<script setup>
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
</script>

<template>
	<nav class="side_bar w-2/12 flex text-white flex-col gap-5 items-center py-5">
		<img src="../assets/logo.png" alt="Logo do São Roque" class="w-10/12">
		<menu class="flex-col flex items-center  justify-center">
			<RouterLink to="/pedidos" class="hover:scale-110 hover:text-stone-300 duration-150">Pedidos</RouterLink>
			<RouterLink to="/compras" class="hover:scale-110 hover:text-stone-300 duration-150">Compras</RouterLink>
			<RouterLink to="/inventarios" class="hover:scale-110 hover:text-stone-300 duration-150">Inventários</RouterLink>
			<RouterLink to="/pedidos" class="hover:scale-110 hover:text-stone-300 duration-150">Performances</RouterLink>
		</menu>
		<small class="absolute bottom-2 text-white">V-1.0</small>
	</nav>
</template>

<style scoped>
.side_bar{
	background-color: #00063D;
}
</style>

// sr_panel/src/routes/SideBar.svelte
<script>
	const titulos = ["Pedidos", 'Compras', 'Inventários', 'Performances']
	const urls = ["/pedidos", '/compras', '/inventarios', 'performances']
</script>

<aside class="shadow-2xl text-white text-xl py-4 bg-sky-950 w-2/12 flex flex-col items-center">
	<a class="py-3 w-9/12" href="/"><img src="./logo.svg"  alt="Logo da São Roque"></a>
	<ul class="flex flex-col py-3">
		{#each titulos as titulo,index}
			<li class="self-center transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-125 duration-300">
				<a class="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-125 duration-300" href="{urls[index]}">{titulo}</a>
			</li>
		{/each}
	</ul>
	<small class="self-start absolute bottom-0 px-3 py-3">V-1.0</small>
</aside>
